; total_points =  Total number of stars to generate in the galaxy.
; num_arms = Number of spiral arms in the galaxy (only applicable for spiral galaxies).
; pitch_angle_degrees = Pitch angle of the spiral arms in degrees (only applicable for spiral galaxies).
; min_distance =  Minimum distance between any two stars to avoid overlap.
; radius_limit = Maximum radius of the galaxy.
; galaxy_type = spiralType of the galaxy. Can be 'spiral', 'elliptical', or 'irregular'.
[galaxy]
total_points = 600
num_arms = 4
pitch_angle_degrees = 25.0
min_distance =  1.5
radius_limit = 50.0
galaxy_type = elliptical

;  List of wormhole pairs, where each pair connects two stars by their indices.
[wormholes]
pairs = [[1,10],[2,20],[8,100],[120,150]]

; [player_positioning] section contains parameters related to player positioning in the galaxy.
; num_players: Number of players in the game.
; max_dist_to_neighbor: Maximum radius within which a player can be placed from another player. This value should be optimized based on the radius_limit and the number of players. The optimal value is automatically applied as the minimum of 60% of the radius_limit and the radius_limit divided by the square root of the number of players if the value supplied here is greater than the optimal value.
[player_positioning]
num_players = 10
max_dist_to_neighbor = 100


; [player_initial_resource] section contains initial resources for players.
; r: Initial amount of resource 'r'.
; g: Initial amount of resource 'g'.
; e: Initial amount of resource 'e'.
; i: Initial amount of resource 'i'.
; s: Initial amount of resource 's'.
; st: Initial amount of resource 'st'.
[player_initial_resource]
r =  49
g =  0
e =  200
i =  600
s =  500
st =  300
